# Generated by Django 5.1.1 on 2024-09-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_orders_items_remove_orders_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
